### ISSUE TITLE
教务系统登录需要输入验证码

### ISSUE THREAD

**Issue by CHZarles** [EddieIvan01/Lessons_Robber#2]
发现了一些问题:
运行rob.py不能正常登录。
在config.json里配置错误学号密码，会显示登陆成功，然后报错。

**Comment by EddieIvan01** [comment]
验证码为前一周内正方加入的功能，简单灰化+二值处理即可识别

或

+ 启动时imshow验证码手动输入（better）

+ 手动登录拿Cookie
